services:
  - type: cron
    name: reddit-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    schedule: "0 1 * * *"  # 每天 UTC 01:00 (北京时间 09:00)
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GNEWS_API_KEY
        sync: false
